### ISSUE TITLE
Integrate methods?

### ISSUE THREAD

**Issue by Ironholds** [jumpingrivers/datasauRus#14]
Would it be fun if I integrated the methods so people could generate their own datasets?

**Comment by stephlocke** [comment]
I love this idea! Happy for it to go in the same package or if the code generalises well it could go in a separate package.

I guess depending on how they've done it, easiest thing would be a reticulate call to the python package

**Comment by Ironholds** [comment]
It actually looks really simple and numpy-y, so should be simple to translate. Let me snoop through the code a bit more.

**Comment by Ironholds** [comment]
Ack, I proobably won't have time for this - got some open issues to clear :|

**Comment by maelle** [comment]
I can't access the code at the moment, since the URL in the paper (now behind a paywall) is down:

**Comment by maelle** [comment]
In the meantime I was able to access the paper and to download the code.

- [ ] Write a perturb function
- [ ] Write an isErrorOk function
- [ ] Write a moveRandomPoints function
- [ ] Write a fit function
- [ ] Put all pieces together
- [ ] Test on datasets

**Comment by maelle** [comment]
Not sure this could be part of the next release.

**Comment by stephlocke** [comment]
OK, great work so far! Happy for this to be in the next milestone

**Comment by maelle** [comment]
Creating milestone sounds like a good idea, will do.

**Comment by osheen1** [comment]
Hi @maelle, we can't see the related code for this issue so are going to close.
