### ISSUE TITLE
Add unique dataset identifiers

### ISSUE THREAD

**Issue by stephlocke** [jumpingrivers/datasauRus#15]
This might be something to consider adding https://cran.r-project.org/web/packages/UNF/index.html

**Comment by maelle** [comment]
and the idea would be to write them in the documentation? with an example in the vignette of how to use `identical(unf(iris), unf(iris2))`? or just a link to the `unf` package docs in the vignette?

**Comment by stephlocke** [comment]
Just a link should be fine.

Ideally, we can hand off the UNFs to Justin & co, the original authors, as versions of the datasets that we're all using. These can then go in the DESCRIPTION or wherever you think relevant to up the scholar factor on the package,

**Comment by maelle** [comment]
"UNF can be used, in tandem with a DOI, to form a persistent citation to a versioned dataset."

Not too sure how they're used in combination (would need to look at dataverse code) but to get a DOI the authors of the datasets should upload them to e.g. Figshare.

Or we could do that on their behalf using https://github.com/ropensci/rfigshare (it seems possible cf https://knowledge.figshare.com/articles/item/how-to-upload-and-publish-my-data "You can rearrange the order in which the authors appear and remove yourself as an author if you are uploading on behalf of someone.").

**Comment by maelle** [comment]
then if the datasets had DOI (probably one for the whole bunch of datasets), the DOI would be added to the docs (of the package and of the datasets).

The datasets are in no central platform other than this package at the moment if I followed correctly.

**Comment by stephlocke** [comment]
I've messaged Justin to see if he's willing to get the data on figshare
