### ISSUE TITLE
Broken image (section "Usage")

### ISSUE THREAD

**Issue by GegznaV** [jumpingrivers/datasauRus#32]
On https://itsalocke.com/datasaurus/, the image is broken:
![image](https://user-images.githubusercontent.com/12725868/59926238-93353180-9442-11e9-9add-5e0d3c1150b5.png)

**Comment by stephlocke** [comment]
Thanks for the heads up! We'll look into it ASAP :)

**Comment by Amymcdougall** [comment]
Incorrect path
wants -https://itsalocke.com/datasaurus/README/README-unnamed-chunk-2-1.png

is in - https://github.com/lockedata/datasauRus/blob/gh-pages/articles/Datasaurus_files/figure-html/unnamed-chunk-2-1.png

**Comment by osheen1** [comment]
This has been fixed.
