### ISSUE TITLE
Not taking opportunity of teaching about 'invisible' datapoints

### ISSUE THREAD

**Issue by steltenpower** [jumpingrivers/datasauRus#34]
In a not unusual scatterplot:
- points can be hidden behind/above one or more other points (transparency can help a bit though)

More unusual, but certainly existing:
- points outside visible area
- points bigger than visible area
- points so small no pixel is drawn
- (because of overlapping part of) points drawn in so little pixels, people don't notice them
- points drawn in a color that is the same, or   similar (depending screen, light conditions and eyes) to other colors used

Just a suggestion.
The current alliteration is nice though

**Comment by osheen1** [comment]
Thanks for your suggestion! We're not going to implement this right now.
